config/routes.rb
Rails.application.routes.draw do

  get "home", to:
  'pages#home', as: :home

  get "about", to:
  "pages#about", as: :about

  get "resume", to:
  "pages#resume", as: :resume

  get "services", to:
  "pages#services", as: :services

  get "project", to:
  "pages#project", as: :project

  get "contact", to:
  "pages#contact", as: :contact

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/resume.rb
class Resume < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def resume
  end

  def services
  end

  def project
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navbar.html.erb
<header>
      <div class="container-fluid">
        <%= image_tag("my port logo.png", class: "img-responsive", id: "navbar-logo", width: 100, height: 100) %>
        <nav>
          <ul>
          <li><%= link_to "About me", about_path %></li>
          <li><%= link_to "Say Hello", contact_path %></li>
          <li><%= link_to "My projects", project_path %></li>
          <li><%= link_to "See Resume", resume_path %></li>
          <li><%= link_to "My Offers", services_path %></li>
          </ul>
        </nav>
    </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ElizabethOrjiPortfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-12">
        <!-- This div is centered and takes 6 columns -->
        <%= render 'layouts/navbar' %>

        <%= yield %>
      </div>
    </div>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>
<%= link_to "home", home_path %>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>
<%= link_to "home", home_path %>

app/views/pages/home.html.erb
<svg viewBox="0 0 2000 960">
  <symbol id="s-text">
    <text text-anchor="middle" x="50%" y="80%">I am Elizabeth Orji </text>
    <text text-anchor="middle" x="51%" y="80%">I am Elizabeth Orji </text>

  </symbol>

  <g class = "g-ants">
    <use xlink:href="#s-text" class="text-copy"></use>
    <use xlink:href="#s-text" class="text-copy"></use>
    <use xlink:href="#s-text" class="text-copy"></use>
    <use xlink:href="#s-text" class="text-copy"></use>
    <use xlink:href="#s-text" class="text-copy"></use>
  </g>
</svg>

<div class="waviy">
   <span style="--i:1">A Full</span>
   <span style="--i:2">stack</span>
   <span style="--i:3">Ruby</span>
   <span style="--i:4">on</span>
   <span style="--i:5">Rails</span>
   <span style="--i:6">Developer,</span>
   <span style="--i:7">UX Designer</span>
   <span style="--i:8">and</span>
   <span style="--i:9">Digital</span>
   <span style="--i:10">Marketer</span>

  </div>

app/views/pages/project.html.erb
<h1>Pages#project</h1>
<p>Find me in app/views/pages/project.html.erb</p>
<%= link_to "home", home_path %>

app/views/pages/resume.html.erb
<h1>Pages#resume</h1>
<p>Find me in app/views/pages/resume.html.erb</p>
<%= link_to "home", home_path %>

app/views/pages/services.html.erb
<h1>Pages#services</h1>
<p>Find me in app/views/pages/services.html.erb</p>
<%= link_to "home", home_path %>